import { IMessageApi } from '@common/interfaces/response-api.interface';

export interface IP016ProblemTreeResponse extends IMessageApi {
  respuesta: IItemP016ProblemTreeRespuesta;
}

export interface IItemP016ProblemTreeRespuesta {
  idArbol: number;
  idAnhio: number;
  problemaCentral: string;
  causas: CausaResponse[];
  efectos: EfectoResponse[];
  fechaCreacion: string;
  esquema: IEsquemaResponse;
}
// Generated by https://quicktype.io

export interface IEsquemaResponse {
  idArchivo: number;
  cxNombre: string;
  cxUuid: string;
  dfFechaCarga: string;
  dfHoraCarga: string;
  csEstatus: string;
  cveUsuario: string;
  cxUuidToPdf: null;
}

export interface CausaResponse {
  idNodo: number;
  nivel: number;
  clave: string;
  descripcion: string;
  hijos: Causa[];
}

export interface EfectoResponse {
  idNodo: number;
  nivel: number;
  clave: null;
  descripcion: string;
  hijos: Efecto[];
}

export interface IP016ProblemTreePayload {
  idAnhio: number;
  problemaCentral: string;
  causas: Causa[];
  efectos: Efecto[];
  esquema: IEsquemaPayload;
}

export interface Causa {
  clave: string;
  descripcion: string;
  hijos: Efecto[];
}

export interface Efecto {
  clave: string;
  descripcion: string;
  hijos: Hijo[];
}

export interface Hijo {
  clave: string;
  descripcion: string;
}

export interface IEsquemaPayload {
  uuid: string;
  tipoArchivo: number;
  nombre: string;
}
