export const baseEnvironment = {
  endpoints: {
    auth: {
      host: '${AUTH_API}/api/seguridad',
      host2: '${AUTH_API}/api',
      login: '/autenticarUsuario',
      loginLdap: '/LDAP/autenticarUsuarioLDAP',
      authAlfresco: '/generarAccesoAlfresco',
      consultarFirma: "/consultarFirma",
      roles: {
        path: '/rol',
        consultarTodos: '/consultarTodos',
        consultarPorId: '/consultarPorId/',
        eliminar: '/eliminar/',
        modificar: '/modificar/',
        registrar: '/registrar',
      },
      usuarios: {
        path: '/usuario',
        consultarTodos: '/consultarTodos',
        consultarPorId: '/consultarPorID/',
        eliminar: '/eliminar/',
        modificar: '/modificar/',
        registrar: '/registrar',
      },
    },
    planeacion: {
      cortoPlazo: {
        host: '${CORTO_PLAZO_API}/api',
        proyectos: {
          registrarProyecto: '/formulario-analitico/registrarProyecto',
          consultarProyectoPorID:
            '/formulario-analitico/consultarProyectoPorID/',
          consultarProyectoPorAnhio:
            '/formulario-analitico/consultaProyectosPorAnhio/',
          consultarProyectoPorAnhioCarga:
            '/formulario-analitico/consultaProyectosPorAnhioCarga/',
          modificarProyectoPorID: '/proyecto-anual/modificarProyectosPorID/',
          eliminarProyectoPorID: '/formulario-analitico/eliminarProyectosPorID',
          secuencialProyectoAnual: '/proyecto-anual/secuencialProyectoAnual/',
          excelToMysql: '/proyecto-anual/excelToMysql/',
          consultaProyectosPorAnhioParaValidar:
            '/formulario-analitico/consultaProyectosPorAnhioParaValidar/',
          enviarARevisar: '/proyecto-anual/enviarARevisar',
          enviarAValidacionTectica: '/proyecto-anual/enviarAValidacionTecnica',
          finalizarRegistro: '/proyecto-anual/finalizarRegistro',
          consultaProyectosPorAnhioParaVistaGeneral:
            '/formulario-analitico/consultaProyectosPorAnhioParaVistaGeneral/',
          consultaProyectosPorAnhioParaVistaGeneralPorId:
            '/formulario-analitico/consultaProyectosPorAnhioParaVistaGeneralPorId/',
          consultaProyectosPorAnhioEstatus:
            '/formulario-analitico/consultaProyectosPorAnhioEstatus/',
          consultarProyectoCompleto:
            '/proyecto-anual/consultarProyectoCompleto/',
        },
        actividades: {
          consultarPorProyecto: '/actividades/consultaPorProyecto/',
          consultarPorID: '/actividades/consultarPorID/',
          eliminar: '/actividades/eliminar/',
          modificar: '/actividades/modificar/',
          registrar: '/actividades/registrar',
        },
        productos: {
          registrar: '/productos/registrar',
          modificar: '/productos/modificar/',
          consultarPorId: '/productos/consultarPorID',
          consultaPorActividad: '/productos/consultaPorActividad/',
          eliminar: '/productos/eliminar/',
        },
        mir: {
          path: '/mir',
          consultaTablaMirPorAnhio: '/consultaTablaMirPorAnhio/',
          consultarProductosPorIdAnhio: '/consultarProductosPorIdAnhio/',
        },
        metasbienestar: {
          path: '/cortoplazo/metasbienestar',
          consultarPorAnhio: '/consultarPorAnhio/',
          productosConsultarPorIdCatalogoIndicadorPI:
            '/productos/consultarPorIdCatalogoIndicadorPI/',
        },

        presupuestos: {
          registrar: '/presupuesto/registrar',
          modificar: '/presupuesto/modificar/',
          consultarPorId: '/presupuesto/consultarPorID',
          consultaPorProducto: '/presupuesto/consultarPorProducto/',
          eliminar: '/presupuesto/eliminar/',
        },
        validador: {
          path: '/cortoplazo/validacion',
          consultarRevision: '/consultarRevision/',
          guardar: '/guardar',
        },
        archivoSeccion: {
          path: '/archivo-seccion',
          consultaPorAnhio: '/consultaPorAnhio/',
          registrar: '/registrar',
        },
      },
      medianoPlazo: {
        host: '${MEDIANO_PLAZO_API}/api/medianoplazo',
        host2: '${MEDIANO_PLAZO_API}/api/mp',
        acciones: {
          path: '/accion',
          consultarActivosPorEstrategia: '/consultarActivosPorEstrategia/',
          consultarPorID: '/consultarPorID/',
          eliminar: '/eliminar',
          modificar: '/modificar',
          registrar: '/registrar',
          version: '/version',
          consultarCatalogoAcciones: "/consultarCatalogoAcciones/",
        },
        gestorEstructura: {
          path: '',
          consultarInicioPorID: '/consultarInicioPorID/',
          consultarTodosInicio: '/consultarTodosInicio',
          eliminar: '/eliminar/',
          modificar: '/modificar/',
          registrar: '/registrar',
          consultarInicioPorAnhio: '/consultarInicioPorAnhio/',
          version: '/version',
          consultarInicioPorAnhioPorValidar:
            '/consultarInicioPorAnhioPorValidar/',
          enviarARevisar: '/enviarARevisar/',
          enviarAValidacionTectica: '/enviarAValidacionTecnica',
          finalizarRegistro: '/finalizarRegistro/',
        },
        estrategia: {
          path: '/estrategia',
          consultarActivos: '/consultarActivos/',
          consultarPorID: '/consultarPorID/',
          eliminar: '/eliminar',
          modificar: '/modificar',
          registrar: '/registrar',
          version: '/version',
          consultarCatalogoObjetivos: "/consultarCatalogoObjetivos/",
        },
        objetivo: {
          path: '/objetivo',
          consultarActivos: '/consultarActivos',
          consultarPorID: '/consultarPorID/',
          eliminar: '/eliminar/',
          modificar: '/modificar',
          registrar: '/registrar',
          version: '/version',
          consultarCatalogoObjetivos: "/consultarCatalogoObjetivos/",
        },
        metasBienestar: {
          path: '/metasbienestar',
          consultarPorEstructura: '/consultarPorEstrucura/',
          consultarPorIdMetas: '/consultarPorID/',
          eliminar: '/eliminar/',
          modificar: '/modificar',
          registrar: '/registrar',
        },
        parametro: {
          path: '/parametro',
          consultarPorEstructura: '/consultarPorEstrucura/',
          consultarPorIdParametro: '/consultarPorID/',
          eliminar: '/eliminar/',
          modificar: '/modificar',
          registrar: '/registrar',
          consultarPorIdProyecto: '/consultarPorIdProyecto/',
          consultarPorIdActividad: '/consultarPorIdActividad/',
          consultarCatalogoIndicadores: "/consultarCatalogoIndicadores/",
        },
        epilogoPiActas: {
          path: '/epilogo',
          registrar: '/registrar',
          consultarPorIdEstructura: '/consultarPorIdEstructura/',
        },
        validador: {
          path: '/validacion',
          consultarRevision: '/consultarRevision/',
          guardar: '/guardar',
        },
      },
      presupuestarios: {
        host: '${PRESUPUESTARIOS_API}/api',
        path: '/programas-presupuestales',
        consultas: {
          consultaPorAnhio: '/consultaPorAnhio/',
          finalizarRegistro: '/finalizarRegistro',
          enviarARevisar: '/enviarARevisar',
        },
        mir: {
          path: '/mir',
          consultaPorAnhio: '/consultaPorAnhio/',
          registrar: '/registrar/',
          registrarFicha: '/registrar-ficha/',
          consultarFicha: '/consultar-ficha/',
          consultarCatalogoIndicadores: "/consultarCatalogoIndicadores/",
        },
        o001: {
          consultaPorAnhio: '/consultaPorAnhio/O001/',
          consultaPorId: '/consultaPorId/O001/',
          registrar: '/registrar/o001',
        },
        m001: {
          consultaPorAnhio: '/consultaPorAnhio/M001/',
          consultaPorId: '/consultaPorId/M001/',
          registrar: '/registrar/m001',
        },
        arbolProblema: {
          path: '/arbol-problema',
          consultaPorAnhio: '/consultaPorAnhio/',
          registrar: '/registrar',
        },
        arbolObjetivos: {
          path: '/arbol-objetivo',
          consultaPorAnhio: '/consultaPorAnhio/',
          registrar: '/registrar',
        },
        datosGenerales: {
          path: '/datos-generales',
          consultaPorAnho: '/consultaPorAnho/',
          consultarArchivoPorId: '/consultaArchivosPorId/',
          consultarPorId: '/consultaPorId/',
          consultaPorProgramaPresupuestal: '/consultaPorProgramaPresupuestal/',
          eliminar: '/eliminar/',
          modificar: '/modificar/',
          registrar: '/registrar',
        },
        diagnostico: {
          path: '/diagnostico',
          registrar: '/registrar',
          consultaPorAnho: '/consultaPorAnho/',
        },
        validador: {
          path: '/programacion/validacion',
          consultarRevision: '/consultarRevision/',
          guardar: '/guardar',
        },
      },
    },
    seguimiento: {
      seguimientoAnual: {
        host: '${SEGUIMIENTO_ANUAL_API}/api',
        parametroConsultaByIdProyecto: '/mp/parametro/consultarPorIdProyecto/',
        solicitudSeguimiento: {
          path: '/solicitud-seguimiento',
          // consultaPorAnhio: '/consulta-por-anhio/',
          consultaPorUsuario: '/consulta-por-usuario/',
          registrar: '/registrar',
          secuencialPorAnhio: '/secuencialPorAnhio/',
          consultaPorIdSolicitud: '/consulta-por-id/',
          actualizaPorIdSolicitud: '/actualiza-por-id/',
          cambiarEstatus: '/cambiarEstatus/',
        },
        solicitudComentarios: {
          path: '/solicitud/comentario',
          consultaPorId: '/consultaPorId/',
          consultaPorIdSolicitud: '/consultaPorIdSolicitud/',
          registrar: '/registrar',
          actualizaPorId: '/actualizaPorId/',
          eliminar: '/eliminar/',
        },
        proyectos: {
          path: '/seguimiento/proyecto',
          registrarProyecto: '/registrarProyecto',
          consultarProyectoPorID: '/consultarProyectoPorID/',
          consultarProyectoPorAnhio: '/consultaProyectosPorAnhio/',
          consultarProyectoPorAnhioCarga: '/consultaProyectosPorAnhioCarga/',
          modificarProyectoPorID: '/modificarProyectosPorID/',
          eliminarProyectoPorID: '/eliminarProyectosPorID',
          secuencialProyectoAnual: '/secuencialProyectoAnual/',
          consultaProyectosPorAnhioParaValidar:
            '/consultaProyectosPorAnhioParaValidar/',
          enviarARevisar: '/enviarARevisar',
          enviarAValidacionTectica: '/enviarAValidacionTecnica',
          finalizarRegistro: '/finalizarRegistro',
          consultarProyectos: '/consultarProyectos',
          cancelarProyecto: '/cancelarProyecto',
          consultarProyectoModificacion: '/consultarProyectoModificacion/',
          consultarProyectoCancelacion: '/consultarProyectoCancelacion/',
          eliminarAdecuacion: '/eliminarAdecuacion',
        },
        productos: {
          path: '/seguimiento/productos',
          cancelarProducto: '/cancelarProducto',
          registrar: '/registrar',
          modificar: '/modificar/',
          consultarPorId: '/consultarPorID/',
          consultaPorActividad: '/consultaPorActividad/',
          eliminar: '/eliminar/',
          secuencialPorProyecto: '/secuencialPorProyecto/',
          consultaPorActividadSolicitud: '/consultaPorActividadSolicitud',
          consultaProductoModificacion: '/consultaProductoModificacion/',
          consultaProductoCancelacion: '/consultaProductoCancelacion/',
          eliminarAdecuacion: '/eliminarAdecuacion',
        },
        actividades: {
          path: '/seguimiento/actividades',
          cancelarActividad: '/cancelarActividad',
          consultarPorProyecto: '/consultaPorProyecto/',
          consultarPorID: '/consultarPorID/',
          consultaPorProyectoSolicitud: '/consultaPorProyectoSolicitud?',
          eliminar: '/eliminar/',
          modificar: '/modificar/',
          registrar: '/registrar',
          secuencialPorProyecto: '/secuencialPorProyecto/',
          consultarActividadModificacion: '/consultarActividadModificacion/',
          consultarActividadCancelacion: '/consultarActividadCancelacion/',
          eliminarAdecuacion: '/eliminarAdecuacion',
        },
        acciones: {
          path: '/seguimiento/acciones',
          secuencialPorProducto: '/secuencialPorProducto/',
          consultarAccionesPorId: '/consultarAccionesPorId/',
          consultarAcciones: '/consultarAcciones?',
          registrar: '/registrar',
          modificar: '/modificar/',
          eliminar: '/eliminar/',
          cancelar: '/cancelar',
          consultarAccionesModificacion: '/consultarAccionesModificacion/',
          consultarAccionesCancelacion: '/consultarAccionesCancelacion/',
          eliminarAdecuacion: '/eliminarAdecuacion',
        },
        presupuestos: {
          path: '/seguimiento/presupuesto',
          registrar: '/registrar',
          modificar: '/modificar/',
          consultarPorId: '/consultarPorID',
          consultaPorProducto: '/consultarPorProducto/',
          consultarPresupuestos: '/consultarPresupuestos?',
          eliminar: '/eliminar/',
          cancelar: '/cancelar',
          ampliacionReduccion: '/ampliacion',
          consultarPresupuestoModificacion:
            '/consultarPresupuestoModificacion/',
          registrarAjuste: '/registrarAjuste',
          consultarAjustes: '/consultarAjustes/',
          consultarPresupuestoCancelacion: '/consultarPresupuestoCancelacion/',
          eliminarAdecuacion: '/eliminarAdecuacion',
        },
        adecuacion: {
          path: '/seguimiento/adecuacion',
          cambiarEstatus: '/cambiarEstatus/',
        },
        avances: {
          host: '${SEGUIMIENTO_AVANCES_API}/api/avance-programatico',
          // host: 'http://140.84.191.226:9006/api/avance-programatico',
          hostBase: '${SEGUIMIENTO_AVANCES_API}/api',
          consultarAvance: '/consultar-avance/',
          consultarAvancesPorAnhio: '/consultar-avances',
          consultarEvidenciaMensual: '/consultarEvidenciaMensual/',
          consultarEvidenciaTrimestral: '/consultarEvidenciaTrimestral/',
          registrarEntregables: '/registrarEntregables/',
          registroEvidenciaMensual: '/registroEvidenciaMensual/',
          registroEvidenciaTrimestral: '/registroEvidenciaTrimestral/',
          registroProductoNoProgramado: '/registroProductoNoProgramado/',
          registrarMetaVA: '/registrarMetasVencidasAdelantadas/',
          consultarProductos: '/productos/consultarProductos',
          consultarPAA: '/proyectos/consultarPAA',
          consultarPaaIdUnidad: '/proyectos/consultarPaaIdUnidad',
          consultarActividades: '/actividades/consultarActividades',
          consultarActividadesPorAnhio:
            '/actividades/consultarActividadesPorAnhio',
          productosNoProgramados: '/producto-no-programado/registrarProducto',
          validacion: {
            guardar: '/validacion/guardar',
            consultarRevision: '/validacion/consultarRevision/',
          },
          enviarProyectoRevision: '/proyectos/enviarRevision',
          eliminarAvance: '/avance-programatico/eliminar-avance/',
        },
        estatusPP: {
          host: '${SEGUIMIENTO_AVANCES_API}/api',
          proyectos: '/seguimiento-programatico/proyectos',
          actividades: '/seguimiento-programatico/proyectos',
          productos: '/seguimiento-programatico/actividades',
          datosGenerales: '/seguimiento-programatico/productos',
        },
        solicitudFirma: {
          path: '/solicitud/firma',
          registrar: '/registrar',
          consultaPorId: '/consultaPorId/',
        },
        seguimientoMIRFID: {
          path: '/seguimiento/mir-fid/planeacion',
          consultaMirPorAnhio: '/consultaMirPorAnhio/',
          consultarJustificacionIndicador: '/justificacion/indicador/',
          consultarJustificacionActividad: '/justificacion/actividad/',
          justificacionActividad: '/justificacion/actividad',
          justificacionIndicador: '/justificacion/indicador',
          consultaJustifiaciones: '/consultarJustificaciones/',
          m001: {
            path: '/seguimiento/mir-fid/actividad',
            justificacionActividadMir: '/actividad-m001',
            justificacionMetaMir: '/meta-m001',
            consultaMir: '/consulta-m001/',
            consultaTodos: '/consulta-todos-m001/'
          },
          o001: {
            path: '/seguimiento/mir-fid/actividad',
            justificacionActividadMir: '/actividad-o001',
            justificacionMetaMir: '/meta-o001',
            consultaMir: '/consulta-o001/',
            consultaTodos: '/consulta-todos-o001/'
          }
        },
        seguimientoMedianoPlazo: {
          path: '/archivos-mediano-plazo',
          consultaPorAnhio: '/consultaPorAnhio/',
          registrar: '/registrar',
        },
      },
    },
    evaluacion: {
      host: '${EVALUACION_API}/api',
      encuestas: {
        path: '/encuestas',
        consultar: '/consultar',
        registrar: '/registrar',
        eliminar: '/{id}/eliminar',
      },
      evaluacionExterna: {
        path: '/evaluacionExterna',
        aspectosMejConsultar: '/aspectos-mejorables/consultar',
        aspectosMejRegistrar: '/aspectos-mejorables/registrar',
        aspectosMejEliminar: '/aspectos-mejorables/{id}/eliminar',
        informesConsultar: '/informes/consultar',
        informesResgistrar: '/informes/registrar',
        informesEliminar: '/informes/{id}/eliminar',
      },
      evaluacionInterna: {
        path: '/evaluacionInterna',
        desempenioConsultar: '/desempenio/consultar',
        desempenioRegistrar: '/desempenio/registrar',
        desempenioEliminar: '/desempenio/{id}/eliminar',
        evidenciaAutoConsultar: '/evidencia-autoevaluacion/consultar',
        evidenciaAutoRegistrar: '/evidencia-autoevaluacion/registrar',
        evidenciaAutoEliminar: '/evidencia-autoevaluacion/{id}/eliminar',
        informeAutoConsultar: '/informe-autoevaluacion/consultar',
        informeAutoRegistrar: '/informe-autoevaluacion/registrar',
        informeAutoEliminar: '/informe-autoevaluacion/{id}/eliminar',
      },
    },
    reportes: {
      numeralia: {
        host: '${NUMERALIA_API}/api',
        reportes: {
          path: '/reportes',
          paaGeneral: '/paa/general/',
          alineacion: '/alineacion/general/',
          adecuaciones: '/adecuaciones/general/',
          seguimiento: '/seguimiento/general/',
          presupuesto: '/presupuesto/general/',
        },
        extractores: {
          path: '/extractores',
          paaaprobado: '/paaaprobado',
        },
        archivoSeccion: {
          path: '/archivo-seccion',
          consultaPorAnhio: '/consultaPorAnhio/',
          registrar: '/registrar',
        },
      },
    },
    notificador: {
      host: '${NOTIFICADOR_API}/api',
      cuentas: '/notificador/cuentas',
    },
    catalogs: {
      host: '${CATALOGOS_API}/api',
      path: '/catalogos/consultarOpcion/',
      configuration: {
        unidades: {
          path: '/unidades',
          actualizarUnidad: '/actualizarUnidad/{idUnidad}?',
          agregarUnidad: '/agregarUnidad',
          consultarActivos: '/consultarActivos',
          consultarUnidadPorID: '/consultarUnidadPorID/',
          eliminarUnidad: '/eliminarUnidad/',
        },
        direcciones: {
          path: '/Direcciones',
          actualizarDirecciones: '/actualizarDirecciones/',
          agregarDireccion: '/agregarDireccion',
          eliminarDireccion: '/eliminarDireccion/',
          listarDirecciones: '/listarDirecciones',
          listarDireccionesPorId: '/listarDireccionesPorId/',
        },
        catalogos: {
          path: '/catalogos',
          actualizarCatalogo: '/actualizarCatalogo?idCatalogo=',
          agregarCatalgo: '/agregarCatalogo',
          agregarRegistroCatalgo: '/agregarRegistroCatalogo',
          consultarCatalogoID: '/consultarCatalogoID/',
          consultarCatalogoPadres: '/consultarCatalogoPadres',
          eliminarCatalogo: '/eliminarCatalogo/',
        },
      },
      articulacionActividad: '1',
      categorizacionProducto: '22',
      tipoProductoIntermedio: '26',
      tipoProductoFinal: '55',
      tipoProductoPeriodico: '90',
      estatusProducto: '96',
      tipoNivelEducativo: '101',
      CampoAccionPreponderanteDirigido: '112',
      actorEducativoPreponderante: '121',
      ambitoParticipacionResponsabilidad: '130',
      continuidadOtrosProductosAnhosAnteriores: '136',
      centrosCosto: '224',
      catalogoPartidasPresupuestales: '232',
      macroprocesos: '587',
      objetivosPrioritario: '592',
      problematicaEducativa2: '599',
      indicadorPI: '606',
      nombreIndicadorMIR: '625',
      accionPuntualPI: '640',
      alineacionPND: '693',
      nivelDesagregacion: '697',
      periodicidadFrecuenciaMedicion: '701',
      tipo: '712',
      acumuladoPeriodico: '715',
      unidadMedida: '718',
      periodoRecoleccionDatos: '724',
      dimensionIndicadores: '727',
      disponibilidadInformacion: '732',
      tendenciaEsperada: '745',
      unidadResponsableReportarAvance: '749',
      sector: '751',
      objetivosDesarrolloSustentable: '753',
      estrategiaPrioritaria: '771',
      comportamientoMedicion: '790',
      tipoValorMeta: '793',
      objetivo: '800',
      nivel: '804',
      unidadAdministrativa: '2059',
      contribucionPNCCIMGP: '823',
      alcance: '829',
      reunionesRealizarse: '835',
      categoria: '838',
      anhoPublicar: '845',
      nivelEducativo: '850',
      fuenteFinanciamiento: '855',
      tipoProducto: '858',
      continuidadOtrosProductosAnhosAnteriores2: '907',
      descripcionPartidasPresupuestales: '1623',
      centroCostos: '1990',
      contribucionProgramasEspeciales: '2003',
      tipoIndicadores: '712',
      tipoMedicion: '2072',
      comportamientoIndicador: '2055',
      desagregacionGeografica: '2069',
      tipoAdecuacion: '2222',
      direccionGeneral: '2226',
      apartadoAdecuacion: '2216',
      tipoModificacion: '2208',
      statusSeguimiento: '2235',
      porPublicar: '842',
      tipoPublicación: '2632',
      difusion: '2641',
      tipoDifusion: '2637',
      revisadoJunta: '96',
      periodoTrimestral: '2687',
      periodoSemestral: '2692',
      clavePrograma: '2380',
    },
    alfresco: {
      getAllDocuments:
        '/nodes/:uidContenedor/children?skipCount=:skipCount&maxItems=:maxItems',
      deleteFile: '/nodes/:uid',
      viewOrDownloadFile: '/nodes/:uid/content',
      uploadFile: '/nodes/:uidContenedor/children',
      requestDownloadFiles: '/downloads',
      statusDownloadFiles: '/downloads/:uid',
    },
  },
  timeReRequestDownloadStatus: 2000,
};
