export const CTipoUsuario = {
  SUPERUSUARIO: 'SUPERUSUARIO',
  ADMINISTRADOR: 'ADMINISTRADOR',
  CONSULTOR: 'CONSULTOR',
  ENLACE: 'ENLACE',
  SUPERVISOR: 'SUPERVISOR',
  PLANEACION: 'PLANEACION',
  PRESUPUESTO: 'PRESUPUESTO',
};
